artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/dataingestion
  data_url: "https://drive.google.com/file/d/1ey81m--C6Gm8cn8bkUExg2h3e29Vj_ro/view?usp=sharing"
  data_zip_path: artifacts/dataingestion/bone_fracture.zip
  unzip_dir: artifacts/dataingestion


prepare_base_model: 
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/model.h5
  updated_model_path: artifacts/prepare_base_model/update_model.h5

model_training: 
  root_dir: artifacts/training
  trined_model_path: artifacts/prepare_base_model/update_model.h5
  final_model_path: artifacts/training/best_model.h5
  train_data_path: artifacts/dataingestion/BONE/Train
  valid_data_path: artifacts/dataingestion/BONE/Validation



